title: Pixel manual-update guide
description: Guide to manually update a potentially modified Google Pixel
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
